# This is just for demo purpose
services:
  mongodb:
      container_name: scoo-mongodb
      image: mongo:5.0
      volumes:
        - ./db-init:/docker-entrypoint-initdb.d
        - ./db-init/data:/tmp/data
      ports:
      - '27017:27017'
  backend:
    container_name: scoosign-backend
    build: "./scoosign-backend"
    image: hadramet/scoosign-backend
    ports:
    - "5000:5000"
    environment:
      - DOTENV_ME=me_21e7c958b7c7ee96346d89001e7c0fbee548a08c2799524869ffda2cb33d7cac
  frontend:
    container_name: scoosign-frontend
    build: "./scoosign"
    image: hadramet/scoosign-frontend
    ports:
    - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URI=http://${BACKEND_URI_EXTERNAL_URI}:5000
    depends_on:
      - backend
